### ISSUE TITLE
[bug] "show info" don't do was is expected 

### ISSUE THREAD

**Issue by Nanomani** [kcook98765/plugin.program.shortlist#4]
"show info" don't do was is expected. When I use "show info" on a movie in a shortlist nothing is show. The movie go to end list.

To reproduce : 

1. open addon "shortlist"
2. open one of custom "shortlist" with movies in
3. select an movie and make a long press to have the context menu
4. chose "show info"
5. then the movie selected is moved at the end of list like with the menu "move to bottom"

anyway I can live with that is not a big deal... :)

**Comment by kcook98765** [comment]
Thanks for the steps. I can reproduce, so I will be able to look into this and likely fix it. Probably by end of the week.

**Comment by kcook98765** [comment]
I have fixed the "Show Info" context menu action.

**Comment by Nanomani** [comment]
I confirm all works fine now.
Thanks :)
