### ISSUE TITLE
[request] add feature "rename shortlist"

### ISSUE THREAD

**Issue by Nanomani** [kcook98765/plugin.program.shortlist#5]
having the ability to rename a short list would be appreciated.

If complicated or if you have not time for that. Please feel free to close this request.

Thank you again for this addon

**Comment by kcook98765** [comment]
I will look into the feasibility of doing this as I work on the other issue this week.

**Comment by kcook98765** [comment]
I have added "Rename Shortlist" option.

**Comment by Nanomani** [comment]
Tested, this is perfect and really usefull.
with "resource.language.fr_fr" updated too :)
Thanks a lot
